version: '3.1'
services:
  app:
    build: .
    environment:
      NODE_ENV: dev
    command: npm run dev
    ports:
      - '8000:8000'
    tty: true
    depends_on:
      - mysql
    volumes:
      - .:/home/banana/banana_tcc:delegated
      - notused:/home/banana/banana_tcc/node_modules
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: banana
      MYSQL_PASSWORD: senha_banana
      MYSQL_DATABASE: teste
volumes:
    notused:
