version: '3.1'
services:
  app:
    build: .
    environment:
      NODE_ENV: dev
    command: npm run test-integration
    ports:
      - 8000:8000
    tty: true
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: banana
      MYSQL_PASSWORD: senha_banana
      MYSQL_DATABASE: tcc_help
