version: '3.1'
services:
  app:
    build: .
    environment:
      NODE_ENV: dev
    command: npm run dev
    ports:
      - 8000:8000
    tty: true
    depends_on:
      - mysql
    volumes:
      - .:/home/banana/banana_tcc:delegated
      - notused:/home/banana/banana_tcc/node_modules
  angular:
    build: client/
    environment:
      NODE_ENV: dev
    ports:
      - 4200:4200
      - 49153:49153
    tty: true
    depends_on:
      - app
    volumes:
      - ./client/:/home/banana/banana_tcc/client:delegated
      - notused2:/home/banana/banana_tcc/client/node_modules
  mysql:
    image: mysql
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: banana
      MYSQL_PASSWORD: senha_banana
      MYSQL_DATABASE: tcc_help
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
volumes:
    notused:
    notused2:
    database:
