version: '2'
services:
  app:
    restart: always
    build: .
    environment:
      NODE_ENV: dev
    command: npm run dev
    ports:
      - '8000:8000'
    tty: true
    depends_on:
      - mysql
    volumes:
      - .:/home/banana/banana_tcc
      - /home/banana/banana_tcc/node_modules
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: banana
      MYSQL_PASSWORD: senha_banana
      MYSQL_DATABASE: teste
