#! /bin/bash

checkDocker=$(docker ps | grep tcchelp_app_1);
if [[ -z checkDocker ]]; then
    echo -e "\e[31mSE FUDEU! A APLICACAO DEVE ESTA RODANDO...\e[0m"
    exit 1;
fi
docker exec -e "TERM=xterm-256color" tcchelp_app_1 npm run lint
return=$?

echo
echo
echo
if [[ $return == 0 ]]; then
    echo -e "\e[32mQUE ISSO EM FILHAO..."
    echo -e "\e[32mCOMMIT REALIZADO COM SUCESSO"
else
    echo -e "\e[31mSE FUDEU!\e[0m"
    echo -e "\e[31mCOMMIT NAO REALIZADO, ARRUME OS ERROS ACIMA, E REEXECUTE GIT ADD E GIT COMMIT\e[0m"
fi
echo
echo
echo
exit $return