#! /bin/bash

docker exec -it -e "TERM=xterm-256color" tcchelp_app_1 npm run lint
return=$?

echo
echo
echo
if [[ $return == 0 ]]; then
    echo -e "\e[32mCOMMIT REALIZADO COM SUCESSO"
else
    echo -e "\e[31mCOMMIT NAO REALIZADO, ARRUME OS ERROS ACIMA\e[0m"
fi
echo
echo
echo
exit $return